pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - '#approved-reviews-by>=1'
      - 'status-success=Analyze (javascript)'
      - status-success=netlify/avocadotoast/deploy-preview
      - status-success=build
    actions:
      merge:
        method: squash
      delete_head_branch:
